name: Dockerise frontend & backend

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  containerise:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps: 
      - name: containerise
        uses: actions/checkout@v4

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        run: npm ci

      # Build and push frontend Docker image
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t sss-frontend:prod .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag sss-frontend:latest ${{ secrets.DOCKER_USERNAME }}/sss-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sss-frontend:latest

      - name: Jenkins
        run: |
          CRUMB=$(curl -u ash:{{secrets.JENKINS_API_TOKEN}} -s 'https://jenkins.netbuildertraining.com/crumbIssuer/api/json' | grep -o '"crumb":"[^"]*"' | cut -d':' -f2 | tr -d '"')
          curl -u ash:{{secrets.JENKINS_API_TOKEN}} -H "Jenkins-Crumb: $CRUMB" -X POST 'https://jenkins.netbuildertraining.com/job/Sanju-deployment-pipeline/build'
