name: Dockerise frontend & backend

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  containerise:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps: 
      - name: containerise
        uses: actions/checkout@v4
    
      # Install frontend dependencies
      - name: Install Frontend Dependencies
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: asharubendy
          password: ${{ secrets.GHCR }}

      - name: Create Prod Docker image
        uses: docker/build-push-action@v5
        with:  
          platforms: linux/amd64
          push: true
          tags: ghcr.io/asharubendy/sss-frontend:prod
          cache-from: type=gha
          cache-to: type=gha
      
      - name: Jenkins
        run: |
          CRUMB=$(curl -u ash:{{secrets.JENKINS_API_TOKEN}} -s 'https://jenkins.netbuildertraining.com/crumbIssuer/api/json' | grep -o '"crumb":"[^"]*"' | cut -d':' -f2 | tr -d '"')
          curl -u ash:{{secrets.JENKINS_API_TOKEN}} -H "Jenkins-Crumb: $CRUMB" -X POST 'https://jenkins.netbuildertraining.com/job/Sanju-deployment-pipeline/build'
  