name: Dockerised Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Install MongoDB tools for interacting with the database
    - name: Install mongosh
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-mongosh mongodb-org-tools
    # MongoDB setup
    - name: MongoDB Setup
      uses: supercharge/mongodb-github-action@v1
      with:
        mongodb-version: latest

    # Load codes into MongoDB
    - name: Load codes into MongoDB
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        mongoimport --uri "${{ secrets.MONGO_URI }}" --collection codes --file ./mongo/country-code.codes.json --jsonArray

    # Load services into MongoDB
    - name: Load services into MongoDB
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        mongoimport --uri "${{ secrets.MONGO_URI }}" --collection streamingservices --file ./mongo/country-code.streamingservices.json --jsonArray

    # Clone the backend repository
    - name: Checkout Backend Repository
      uses: actions/checkout@v4
      with:
        repository: SSG27/EXPRESS-API
        path: backend

    # Install backend dependencies
    - name: Install Backend Dependencies
      run: npm ci --legacy-peer-deps
      working-directory: ./backend

    # Start the backend server
    - name: Start Backend
      run: npm start &
      working-directory: ./backend

    # Wait for the backend to be ready (adjust the wait time as necessary)
    - name: Wait for Backend to be Ready
      run: sleep 15

    # Install frontend dependencies
    - name: Install Frontend Dependencies
      run: npm ci

    # Run frontend linting
    - name: Run Frontend Lint
      run: npm run lint

    # Start the frontend server
    - name: Start Frontend
      run: npm run dev &
      
    # Wait for the frontend to be ready
    - name: Wait for Frontend to be Ready
      run: sleep 15

    # Install Playwright browser
    - name: Install Chromium Playwright Browser
      run: npx playwright install chromium --with-deps

    # Debugging
    - name: Debugging
      run: sudo lsof -i -P -n | grep LISTEN

    # Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test

    # Upload Playwright report
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30